services:
  - type: web
    name: palpiteiro-ia-backend
    env: docker
    plan: starter
    branch: main
    rootDir: .
    healthCheckPath: /health
    dockerCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
